### ISSUE TITLE
Permission denied on --enable-debug=no

### ISSUE THREAD

**Issue by xaionaro** [xaionaro/clsync#133]
rsync: change_dir "/home/xaionaro/clsync/examples/testdir/from" failed: Permission denied (13)
    rsync: change_dir#1 "/home/xaionaro/clsync/examples/testdir/to/" failed: Permission denied (13)
    rsync error: errors selecting input/output files, dirs (code 3) at main.c(631) [Receiver=3.1.1]
    Error: Got non-zero exitcode 3 from __sync_exec().
    Error: Got error-report from exitcode_process().
    Exitcode is 3, strerror(3) returns "No such process". However strerror() is not ensures compliance between exitcode and error description for every utility. So, e.g if you're using rsync, you should look for the error description into rsync's manpage ("man 1 rsync"). Also some advices about diagnostics can be found in clsync's manpage ("man 1 clsync", see DIAGNOSTICS)
    Warning: __sync_exec_thread(): Bad exitcode 3 (errcode 3). Give up.
    Error: Bad exitcode 3 (errcode 3)
    Error: Got error from thread #0: errcode 3. (4: Interrupted system call)
    Error: got error while sync_idle(). (4: Interrupted system call)

Reported by @bircoph

**Comment by bircoph** [comment]
Looks like capabilities code is responsible: with --disable-capabilities clsync works fine.

**Comment by xaionaro** [comment]
Thanks! Found:

    privileged.c:1066:debug(4, "setuid(%u) == %i", exec_uid, setuid(exec_uid));
