### ISSUE TITLE
Build failure on ~x86: privileged.c:120:2631: error: ‘__NR_shmdt’ undeclared here (not in a function)

### ISSUE THREAD

**Issue by bircoph** [xaionaro/clsync#137]
privileged.c:120:2631: error: ‘__NR_shmdt’ undeclared here (not in a function)
  FILTER_TABLE_NONPRIV
         ^
privileged.c:125:2: error: initializer element is not constant
  FILTER_TABLE_NONPRIV
  ^
privileged.c:125:2: error: (near initialization for ‘filter_w_mprotect_table[51].k’)
Makefile:931: recipe for target 'clsync-privileged.o' failed
make[2]: *** [clsync-privileged.o] Error 1

**Comment by bircoph** [comment]
Hmm, how can I attach a text file here (the full build log)?

**Comment by bircoph** [comment]
It seems github can't handle that.
So let it be here:
ftp://arcueid.brunestud.info/gentoo/clsync-9999.build.log

**Comment by bircoph** [comment]
More meaningful messages with make -j1:

i686-pc-linux-gnu-gcc -std=gnu99 -std=gnu99 -DHAVE_CONFIG_H -I.  -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include   -DREVISION=\".19\" -DTHREADING_SUPPORT  -DINOTIFY_SUPPO
RT      -DBACKTRACE_SUPPORT -DCAPABILITIES_SUPPORT -DSECCOMP_SUPPORT -DGETMNTENT_SUPPORT -DUNSHARE_SUPPORT -DPIVOTROOT_OPT_SUPPORT -DCGROUP_SUPPORT -DHL_LOCKS -march=native -
m32 -O2 -funswitch-loops -fpredictive-commoning -ftree-vectorize -ftree-slp-vectorize -fvect-cost-model  -fgcse-after-reload -ftree-partial-pre -ftree-loop-im -fweb -frename-
registers -fomit-frame-pointer  -mfpmath=sse -pipe -frecord-gcc-switches -fno-stack-protector -ggdb3 -pthread -c -o clsync-privileged.o `test -f 'privileged.c' || echo './'`p
rivileged.c 
In file included from privileged.c:64:0:
privileged.c:80:34: error: ‘__NR_shmdt’ undeclared here (not in a function)
  BPF_JUMP(BPF_JMP+BPF_JEQ+BPF_K, __NR_##syscall, 0, 1), \
                                  ^
privileged.c:109:2: note: in expansion of macro ‘SECCOMP_ALLOW_ACCUM_SYSCALL’
  SECCOMP_ALLOW_ACCUM_SYSCALL(shmdt),    \
  ^
privileged.c:120:2: note: in expansion of macro ‘FILTER_TABLE_NONPRIV’
  FILTER_TABLE_NONPRIV
  ^
privileged.c:125:2: error: initializer element is not constant
  FILTER_TABLE_NONPRIV
  ^
privileged.c:125:2: error: (near initialization for ‘filter_w_mprotect_table[51].k’)
Makefile:931: recipe for target 'clsync-privileged.o' failed
make[2]: *** [clsync-privileged.o] Error 1

**Comment by bircoph** [comment]
The full log for -j1 build:
ftp://arcueid.brunestud.info/gentoo/clsync-9999.build.log-2

**Comment by bircoph** [comment]
Ok, I got something, in notation (a <-b ) meaning (a includes b) we have:
syscall.h <- sys/syscall.h <- asm/unistd.h

On x86 asm/unistd.h includes asm/unistd_32.h, on amd64 asm/unistd_64.h
unistd_64.h contains shmdt syscall, while unistd_32.h doesn't.

You should probably remove unsupported syscalls depending on arch and add replacements if any.

**Comment by bircoph** [comment]
I'm not sure why shmdt was added in the first place.

**Comment by xaionaro** [comment]
> You should probably remove unsupported syscalls depending on arch and add replacements if any.

`shmdt()` does *not* depend on arch, AFAIK. Need some time for tests.

**Comment by xaionaro** [comment]
A test program on Debian i386 result:

    ~# strace ./a.out 2>&1 | grep shm
    shmget(IPC_PRIVATE, 1024, IPC_CREAT|0666) = 1946779701
    shmat(1946779701, 0, 0)                 = 0xf779e000
    shmdt(0xf779e000)                       = 0

I mean `shmdt()` is really there. Just __NR_shmdt is not defined by some unknown reason.

**Comment by xaionaro** [comment]
I don't the right way to fix that. The syscall is there, but there's no constant to be used in the seccomp bpf rules. I can suggest to do not compile with seccomp support on i386.

**Comment by bircoph** [comment]
>  can suggest to do not compile with seccomp support on i386.

Can't agree here. Chrome and other seccomp-powered projects work on x86, so this is doable.

**Comment by xaionaro** [comment]
> Can't agree here. Chrome and other seccomp-powered projects work on x86, so this is doable.

1. I thought Chrome doesn't support "x86".
2. Chrome has a huge team to support their hacks.
3. Not every program uses `shmat()`/`shmdt()`.

**Comment by xaionaro** [comment]
Fixed by adding a "#define" with "#warning".
