### ISSUE TITLE
sync-handler echo generates a file with absolut filenames and relativ filenames

### ISSUE THREAD

**Issue by fabianito** [xaionaro/clsync#153]
Hi, 
we try to generate a List of Files for rsync.
We use this command:

" clsync -M simple -S echo -l test --skip-initialsync -W ~/clsynctest -D ~/clsynctemp/ | tee -a ~/cllog2.txt"
In clog2.txt we see both - absolut and relativ filenames:

sync test 256 /home/testuser/clsynctest/tests/phpunit/includes/upload/UploadStashTest.php
sync test 256 /home/testuser/clsynctest/tests/phpunit/includes/upload/UploadBaseTest.php
sync test 256 /home/testuser/clsynctest/tests/phpunit/includes/upload/UploadFromUrlTest.php
sync test 1073741828 tests/phpunit/includes/upload
sync test 256 resources/lib/oojs-ui/themes/apex/images/icons/feedback-ltr.png
sync test 2 resources/lib/oojs-ui/themes/apex/images/icons/feedback-ltr.png
sync test 4 resources/lib/oojs-ui/themes/apex/images/icons/feedback-ltr.png
sync test 8 resources/lib/oojs-ui/themes/apex/images/icons/feedback-ltr.png

It's a syntax error from our command or a bug?

inotifywait generate only absolut filenames

I know - clsync have the options "-U" to don't unlink the filelist for rsync. But this filelist is only 3000 Filenames - but we extract 14.000 Files from the tar archiv.
We use this command:
"clsync -K example-simple -M rsyncdirect -w2 -t5 -l test -U -W ~/clsynctest -D ~/clsynctemp/"

**Comment by xaionaro** [comment]
Hello.

> It's a syntax error from our command or a bug?

`simple` mode should show absolute paths. Seems to be a bug. It was fixed 10 months ago and pushed to the `master` branch. Sorry, forgot to make a release :)

Try to use the version from the `master` branch:

```
apt-get install -y dpkg-dev libcgroup-dev libcap-dev libglib2.0-dev
git clone https://github.com/xaionaro/clsync
cd clsync
dpkg-buildpackage -rfakeroot
dpkg -i ../clsync_*.deb
```

> I know - clsync have the options "-U" to don't unlink the filelist for rsync. But this filelist is only 3000 Filenames - but we extract 14.000 Files from the tar archiv.

* I can try option `--rsync-prefer-include`. I don't recommend you to use it, but it can be useful for debugging.
* Try to fix `fs.inotify.max_queued_events` value (`sysctl fs.inotify.max_queued_events=65536`).
* You can add something like `-d3` to see which events clsync gets.
* (the most important:) some of that filenames are directories that should be synced recursively (without listing every file in the directories).

**Comment by fabianito** [comment]
Hi xia,

great! Thank you for your fast help :) 
I take the master branch - it works! Thnaks!

Best Regards,
Fabian
