### ISSUE TITLE
How to kill the process and pid file?

### ISSUE THREAD

**Issue by vebmaster** [xaionaro/clsync#159]
Hello.
I start the synchronization process. But the process does not end in
`kill $(cat /var/run/clsync.pid)`
PID file is not deleted.
When restarting crontab - I can’t check if the clsync process is running.
If the process crashes, I can’t check if the process is running or not.
______
Здравствуйте.
Запускаю процесс синхронизации. Но процесс не завершается через 
`kill $(cat /var/run/clsync.pid)`
PID файл не удаляется.
При повторном запуске crontab - я не могу проверить, запущен ли процесс clsync.
Если процесс аварийно упадёт, я не могу проверить, запущен ли процесс или нет

**Comment by xaionaro** [comment]
Hello. Despite the fact my native language is Russian, it would be better to use English to be connected with world-wide community :)

clsync-related comments:
* The pidfile is created by `clsync` or by your service manager?
* Could you please copy here how do you run `clsync`?
* You can run it with `-d9` to see what does it do instead of dying and deleting the pidfile. Also you can use `-Ysyslog` or `-Ystderr` to control where you want to receive this logs.
* I doubt you will use this way, but you may also use an unix socket (option `--socket` of clsync) instead of pidfile. It allows you to send a command to clsync to die through this socket (I can prepare a tool which will send this signal if you like). Or you can just find the process-owner of the socket and kill it by pid:
```bash
mkdir /tmp/{2,3}
clsync --socket /tmp/test.sock -W /tmp/2/ -D /tmp/3/
fuser -15 -k /tmp/test.sock # it will kill the clsync above
```

Just a common-sysadmin-related comment:
* Some sysadmins traces if the process is still alive (and it's `pid`) using `cgroups`.

I would be glad to help to handle clsync. If the problem is still actual then please let me know the answers for my questions above.

**Comment by vebmaster** [comment]
Здравствуйте Дмитрий.
С английском я на вы, через переводчик, поэтому попробую хотябы на русском правильно написать сообщение :)
Проблема всё таки осталась. Предположительно это бага. Файл сокета остаётся и процесс так же висит. Убивается только через 9 сигнал (kill -9).
Спасибо за совет работы через socket, это ещё лучше. Для поддержки socket пересобрал clsync
```
./configure --enable-socket --enable-socket-library
```

Причиной использовать clsync послужило потребность двухсторонней синхронизации (репликации)  папки сайта на двух серверах, расположенных в разных ЦОД. Файлов в папке около 60 000. Тестирование проходит по принципу недоступности одного из серверов. Текущий описываемый далее пример основан на запуске clsync только на первом сервере.
1) запустил программу синхронизации (clsync) на первом сервере (s1)
2) выключаю сеть (или сервис rsync) на втором сервере (s2)
3) на первом сервере (s1) создаю пару папок или файлов для создания события синхронизации
4) жду какое то время = эмуляция недоступности сервера. В это время clsync пытается подключиться ко второму серверу (s2) и синхронизировать файлы/папки.
5) пытаюсь закрыть приложение clsync по сокету через fuser: `fuser -15 -k /var/run/clsync1.sock`

**Comment by vebmaster** [comment]
Здравствуйте Дмитрий.
С английском я на вы, через переводчик, поэтому попробую хотябы на русском правильно написать сообщение :)
Проблема всё таки осталась. Предположительно это бага. Файл сокета остаётся и процесс так же висит. Убивается только через 9 сигнал (kill -9).
Спасибо за совет работы через socket, это ещё лучше. Для поддержки socket пересобрал clsync
```
./configure --enable-socket --enable-socket-library
```

Причиной использовать clsync послужило потребность двухсторонней синхронизации (репликации)  папки сайта на двух серверах, расположенных в разных ЦОД. Файлов в папке около 60 000. Тестирование проходит по принципу недоступности одного из серверов. Текущий описываемый далее пример основан на запуске clsync только на первом сервере. Синхронизацию делаю через протокол rsync://
1) запустил clsync на первом сервере (s1)
2) останавливаю сервис rsync на втором сервере (s2)
3) на первом сервере (s1) создаю пару папок или файлов для создания события синхронизации
4) жду какое то время = эмуляция недоступности сервера. В это время clsync пытается подключиться ко второму серверу (s2) и синхронизировать файлы/папки.
5) пытаюсь закрыть приложение clsync по сокету через fuser: `fuser -15 -k /var/run/clsync1.sock`
по логам из syslog будет видно, что сигнал получен и дальнейшие действия от clsync не фиксируются.
Пробую закрыть через 2 сигнал
`fuser -2 -k /var/run/clsync1.sock`
Программа так же не закрылась, в логах syslog ничего пишется уже.
Пробую закрыть через 9 сигнал
`fuser -9 -k /var/run/clsync1.sock`
Программа закрылась, в логах syslog ничего пишется уже.
Лог syslog двух разового испытания одного и того же. лог -d9
https://pastebin.com/vgEy81rj
https://pastebin.com/LhAphssS

Подробные действия:
На сервере s1:
`export RSYNC_PASSWORD="1"`
`clsync -w20 -t10 -T10 -d9 -Mrsyncdirect --background --socket /var/run/clsync1.sock --output syslog --ignore-failures --retries=0 --modification-signature '*' -W/mnt/my-sync -Drsync://root@s2:/my-sync`

На сервере "s2":
`service rsync stop`

На сервере s1:
создаю папку 11111111
```
# ps uax |grep clsync
root     15841  0.0  0.1  56972  3312 ?        Ssl  11:03   0:00 clsync -w3 -t3 -T3 -Mrsyncdirect --background --socket /var/run/clsync1.sock --output syslog --ignore-failures --retries=0 --modification-signature * -W/mnt/my-sync -Drsync://root@s2:/my-sync

# fuser -15 -k /var/run/clsync1.sock
/run/clsync1.sock:   15841

# ps uax |grep clsync
root     15841  0.0  0.1  56972  3312 ?        Ssl  11:03   0:00 clsync -w3 -t3 -T3 -Mrsyncdirect --background --socket /var/run/clsync1.sock --output syslog --ignore-failures --retries=0 --modification-signature * -W/mnt/my-sync -Drsync://root@s2:/my-sync

# fuser -2 -k /var/run/clsync1.sock
/run/clsync1.sock:   15841

# ps uax |grep clsync
root     15841  0.0  0.1  56972  3312 ?        Ssl  11:03   0:00 clsync -w3 -t3 -T3 -Mrsyncdirect --background --socket /var/run/clsync1.sock --output syslog --ignore-failures --retries=0 --modification-signature * -W/mnt/my-sync -Drsync://root@s2:/my-sync

# fuser -9 -k /var/run/clsync1.sock
/run/clsync1.sock:   15841

# ls -la /var/run/clsync1.sock
srwxr-xr-x 1 root root 0 янв 10 11:03 /var/run/clsync1.sock
```

Как видно sock файл остался, процесс убился только через 9 сигнал.

В syslog сыпятся вот такие сообщения, он так идентифицирует невозможность подключиться к удалённому rsync серверу:
/vat/log/syslog
```
Jan 10 11:08:39 s1 clsync[15841]: Error: Got non-zero exitcode 10 from __sync_exec().
Jan 10 11:08:39 s1 clsync[15841]: Error: Got error-report from exitcode_process().#012Exitcode is 10, strerror(10) returns "No child processes". However strerror() is not ensures compliance between exitcode and error description for every utility. So, e.g if you're using rsync, you should look for the error description into rsync's manpage ("man 1 rsync"). Also some advices about diagnostics can be found in clsync's manpage ("man 1 clsync", see DIAGNOSTICS)
Jan 10 11:08:39 s1 clsync[15841]: Warning: Bad exitcode 10 (errcode 10). Retrying.
```

Получается, что невозможно по сокету или пид файлу проверить запущен ли процесс или нет.
Мой вариант проверки:
```
	# Провека: запущен ли процесс
	PIDFILE=/var/run/clsync/clsync-${LABEL}.pid
	if [ -f $PIDFILE ]; then
		pid=$(cat $PIDFILE)
		[ -d "/proc/${pid}" ] && continue
	fi
```

**Comment by xaionaro** [comment]
> С английском я на вы, через переводчик, поэтому попробую хотябы на русском правильно написать сообщение :)

OK :)

> Для поддержки socket пересобрал clsync
> ```
> ./configure --enable-socket --enable-socket-library
> ```

Забыл сказать. Да, всё верно :)

> https://pastebin.com/vgEy81rj
> ---
> Jan 10 11:57:50 s1 clsync[15841]: Debug3 (pid: 15841; thread: 0x7f774dcce700): sync_sighandler(): got signal 15. ctx_p->state == 3.
> ...
> Jan 10 11:57:50 s1 clsync[15841]: Debug3 (pid: 15841; thread: 0x7f774dcce700): sync_sighandler(): signal handler closed.
> ...
> Jan 10 11:57:51 s1 clsync[15841]: Debug3 (pid: 15841; thread: 0x7f775058e880): inotify_wait(): select with timeout 9223372036854775806 secs (fd == 4).

Хм, вы правы. Это действительно похоже на bug. Постараюсь сегодня-завтра глянуть как такое могло произойти.

> По наблюдениям выяснил, что если убрать параметр `--retries=0` (т.е. попытка будет только 1 = по умолчанию), то процесс через 15 сигнал закрывается. Но у меня задача другая, поэтому надо постоянно пытаться подключиться и синхронизировать..

ОК, благодарю за наблюдение. Попробуем разобраться.

**Comment by xaionaro** [comment]
@vebmaster :

Я воспроизвёл проблему так:
```
mkdir /tmp/{1,2}
sudo chown root /tmp/2; sudo chmod 0755 /tmp/2
clsync -Ssh -Mdirect -W /tmp/1 -D /tmp/2 -d9 --retries 0 -w1 -t1 -- -c 'sleep 2; exit 1'
```

Действительно не убивалось. Добавил правку в master-ветку, стало убиваться. Проверьте пожалуйста.

**Comment by vebmaster** [comment]
К сожалению проблема воспроизводится именно с сетевой синхронизацией, как в моём примере выше. Можно даже в качестве удалённого сервера взять несуществующий (он же у нас временно недоступен как бы)
`clsync -w20 -t10 -T10 -d9 -Mrsyncdirect --background --socket /var/run/clsync1.sock --output syslog --ignore-failures --retries=0 --modification-signature * -W/mnt/my-sync -Drsync://root@server:/test`

**Comment by vebmaster** [comment]
Спасибо, теперь процесс корректно завершается.
Теперь можно и в продакшн внедрять. Спасибо за clsync, это действительно мощный инструмент. Перетестил кучу разных вариантов, clsync самый правильный и быстрый.
Дмитрий, а cluster функционал как я понял вообще не работает? Для двухсторонней синхронизации.

**Comment by xaionaro** [comment]
> Спасибо, теперь процесс корректно завершается.

Отлично.

> Спасибо за clsync, это действительно мощный инструмент.

И вам спасибо за отчёт об ошибке :)

> Перетестил кучу разных вариантов, clsync самый правильный и быстрый.

Рад, что кому-то пригодилось :)

> Дмитрий, а cluster функционал как я понял вообще не работает? Для двухсторонней синхронизации.

Да, cluster не работает вообще.
