### ISSUE TITLE
two-way file synchronization (cluster)

### ISSUE THREAD

**Issue by vebmaster** [xaionaro/clsync#160]
Hello.
In man https://manpages.debian.org/jessie/clsync/clsync.1 there is mention of cluster functionality marked "not implemented".
--cluster-ip
--cluster-iface
--cluster-port
Is it possible in the current version to use cluster functionality for two-way directory synchronization?
Thanks.

I set up 2-way synchronization as a master-slave for everyone and it works. But it turns out an extra event on the receiving side. The server that received the change also generates an event on the appearance of the file / directory and also sends this change to the same server from where it received the changes.
Despite this nuance, everything works fine.
____
Здравствуйте.
В man https://manpages.debian.org/jessie/clsync/clsync.1 есть упоминания функционала кластера с пометкой "не реализовано". 
--cluster-ip
--cluster-iface
--cluster-port
Возможно ли в текущей версии задействовать функциональность кластера для двух сторонней синхронизации каталога?
Спасибо.

Я настроил у себя 2-стороннюю синхронизацию как master-slave для каждого и это работает. Но получается лишнее событие на принимающей стороне. Сервер, получивший изменение, тоже генерирует событие на появление файла/каталога и тоже отправляет это изменение на тот же сервер, откуда получил изменения.
Не смотря на данный ньюанс, всё прекрасно работает.

**Comment by xaionaro** [comment]
По поводу вашей проблемы с лишним событием:
Да, сейчас clsync не умеет предоставлять двухстороннюю синхронизацию без этого лишних событий. Опция `--modification-signature "*"` помогает избежать колец (ситуации, в которой одно и то же событие прыгает между серверами до бесконечности). Эта опция, грубо говоря, заставляет игнорировать событие, если видит, что файл не поменялся. Таким образом получается сценарий, ровно как вы и описали:
1. На сервере `A` изменился файл. На сервере `A` сгенерировалось событие.
2. Сервер `A` синхронизирует файл на сервер `B`. На сервере `B` сгенерировалось событие.
3. Сервер `B` видит, что у него файл поменялся, и поэтому синхронизирует его на сервер `A` (на самом деле rsync видит, что файл такой же, и не переписывает его на сервере `A`). На сервере `A` сгенерировалось событие из-за обновления метаданных (rsync их обновил).
4. Сервер `A` видит, что файл не поменялся и просто игнорирует это событие (благодаря `--modification-signature "*"`).

Есть, кстати, ещё одна известная проблема с лишними событиями:
При синхронизации файла (допустим `/somepath/somefile`) `rsync` обычно синхронизирует новое содержимое во временный файл рядом (допустим `/somepath/.somefile.1VHal83`), а потом переименовывает с заменой (в `/somepath/somefile`). И вот clsync на стороне второго сервера видит появление этого временного файла (`.somefile.1VHal83`) и пытается его отсинхронизировать на первый сервер. Если нужно/хочется от этого избавится, то есть смысл рассмотреть, например, следующие варианты:
* Тупо запретить синхронизацию файлов `.*.*` (в regexp: `^\..*\..*$`). Могу помочь настроить clsync.
* Использовать опцию rsync `--temp-dir` и убрать эти файлы куда-то туда, где clsync не смотрит (опять же можно правилами определить исключение для конкретной директории). Но чтобы работал rename, нужно, чтобы `--temp-dir` указывал на тот же раздел, куда осуществляется синхронизация.

Если у вас какой-то важный production, то я бы рекомендовал решить эту проблему.

По поводу `cluster`-а:
cluster -- это начатая инициатива по согласовыванию между несколькими `clsync` информации о том, кто к кому что копирует, чтобы избегать вышеуказанных проблем. Однако я `cluster`-код так и не дописал, и вряд ли когда-либо допишу. В моих планах на будущее написать кластерную ФС, которая может работать поверх обычной ФС, вместо продолжения `clsync`. И даже это я сделаю очень нескоро, если вообще сделаю :(

А в clsync я собираюсь лишь исправлять явные баги и активировать fanotify (так как в каком-то из 5.x-ядер его уже исправили).

Полагаю, вопрос исчерпан, поэтому задачу закрываю.

**Comment by vebmaster** [comment]
Спасибо, как оказалось своими потребностями я "исправил" зацикленность появления события.
Мой clsync.conf
```
[mirror]
delay-sync          	= 10
delay-collect       	= 10
delay-collect-bigfile 	= 300
retries             	= 0
output 			= syslog
debug 			= 0
background		= 1
ignore-failures		= 1
socket			= /var/run/clsync/clsync-%label%.sock
pid-file		= /var/run/clsync/clsync-%label%.pid
status-file	        = /var/run/clsync/clsync-%label%.status
lists-dir       	= /tmp/clsync/%label%
modification-signature 	= *
# big files = 5MB
threshold-bigfile	= 5242880
```
А команда запуска rsync в отдельном `clsync-synchandler.sh` выглядит вот так:
`exec rsync --password-file="/etc/rsyncd.pass" -aHusS --delete-during --temp-dir=/tmp/clsync/${LABEL}/tmp "$excludefrom" --include-from="${LISTFILE}" --exclude='*' "$FROM"/ "$TO"/ 2>"${tmpfile}"`
т.к. /tmp это оперативная память, то лучше перенести --temp-dir куда нибудь на сам диск.

**Comment by xaionaro** [comment]
> Поэтому если /tmp это оперативная память, то лучше перенести --temp-dir куда нибудь на сам диск.

Да, если это два разных раздела, то получается, что rsync будет сначала копировать на один раздел, а потом на другой. И пока rsync копирует файл на второй раздел, clsync увидит эти изменения в файле (в процессе копирования rsync-ом) и может начать синхронизировать этот файл на изначальный сервер. Поэтому лучше использовать rename (который достаточно атомарен), а значит нужно всё держать на одном разделе.

Чтобы заставить игнорировать какую-то директорию, можно либо просто к аргументам rsync добавить `--exclude` (clsync будет добавлять в список на синхронизацию, но rsync будет игнорировать), либо самому clsync-у сказать игнорировать. Второе сделано не очень удобно, но делается это примерно так (см. секцию `RULES` в manpage):
```
mkdir -p /etc/clsync/rules
cat > /etc/clsync/rules/ignore-root-dot-rsync-tmp <<EOF
# forbid syncing of /.rsync-tmp/
-*^/.rsync-tmp$

# allow syncing everything else
+*
EOF
```
, после чего добавляется в конфигурацию clsync: 
```
rules-file = /etc/clsync/rules/ignore-root-dot-rsync-tmp
```

**Comment by vebmaster** [comment]
Спасибо,
> Чтобы заставить игнорировать какую-то директорию
Правильно ли я понял, что в моём случае, когда не требуется ничего игнорировать, rules файл не нужен.

**Comment by xaionaro** [comment]
> Правильно ли я понял, что в моём случае, когда не требуется ничего игнорировать, rules файл не нужен.

Верно :)
