### ISSUE TITLE
Error: Insecure: Others have access to directory "/tmp". Exit. (13: Permission denied)

### ISSUE THREAD

**Issue by vebmaster** [xaionaro/clsync#161]
Дмитрий здравствуйте.
Подскажите пожалуйста, по какой причине может возникать при запуске clsync в логах syslog вот такая ошибка:
```Jan 29 10:58:05 server1 clsync[2947]: Error: Insecure: Others have access to directory "/tmp". Exit. (13: Permission denied)```

папка /tmp - это параметр `lists-dir` в `/etc/clsync.conf`
Путь `lists-dir` менял на другие, тоже самое.

**Comment by vebmaster** [comment]
Удалось решить и воспроизвести проблему.
Ошибка возникает, когда clsync установлен из репозитория ubuntu 
```
clsync/bionic,now 0.4.2-1 amd64 
```
но config-block из конфиг файла /etc/clsync/clsync.conf остался новый от сборки из git.
Получается несовместимость каких то параметров. Каких уже не важно, не стал искать.

**Comment by vebmaster** [comment]
решение: проставить права 600 на каталог из `lists-dir`

**Comment by xaionaro** [comment]
Извиняюсь за задержку с ответом. Работы много :)

На самом деле этот параметр вообще выставлять не обязательно. Если он не выставлен, то он самостоятельно использует `mkdtemp` (`man 3 mkdtemp`) для получения временной директории (который сам настраивает права).

**Comment by vebmaster** [comment]
спасибо, понятно.
Но если нужно складировать данные файлы из `lists-dir` для отладки и понимания работы программы, то приходится указывать путь до папки.

**Comment by vebmaster** [comment]
На втором сервере только что тестировал кое что и обнаружил что и права 600 на папку не помогают, помогли **700**.

Ошибка в syslog:
```
Feb  8 20:52:01 srv2 clsync[24761]: Error: Cannot open "/srv/clsync/my-nginx/.clsync-exclist.24761.140350650092672.1581184321.792191091" as file for writing. (13: Permission denied)
Feb  8 20:52:01 srv2 clsync[24761]: Error: Cannot create list-file (13: Permission denied)
Feb  8 20:52:01 srv2 clsync[24761]: Error: got error while sync_idle(). (13: Permission denied)
```
