### ISSUE TITLE
Запуск rsync через exec в clsync-synchandler-rsyncshell.sh не даёт выполнить следующие строки скрипта

### ISSUE THREAD

**Issue by vebmaster** [xaionaro/clsync#162]
Здравствуйте Дмитрий.
Заметил один ньюанс, который не даёт корректно завершиться скрипту `clsync-synchandler-rsyncshell.sh` - это выполнение rsync через exec
```
exec rsync -avH --delete-before "$excludefrom" --include-from="${LISTFILE}" --exclude='*' "$FROM"/ "$TO"/
```

Команда exec - заменяет текущий интерпретатор shell указанной командой.
В результате чего, всё что будет после этой строки никогда не выполнится.

Пример, я использую mktemp для создания временного файла, куда можно записать ошибки от rsync:
```
tmpfile=$(mktemp -p "/srv/clsync/error/" clsync-rsync-"$LABEL".err.XXXXXXXXXX)
cleanup() {
	[[ -s "${tmpfile}" ]] || rm -f "${tmpfile}"
}
trap cleanup EXIT



exec rsync -aHusS --delete-during --temp-dir="${RSYNC_TMP}" "$excludefrom" --include-from="${LISTFILE}" --exclude='*' "$FROM"/ "$TO"/ 2>"${tmpfile}"
```
в этом случае скрипт никогда не создаст событие EXIT, в результате чего временный файл никогда не удалится :)

Решение: запускать `rsync` без `exec`

Если здесь exec преследует другую какую то цель, то подскажите пожалуйста какую? Спасибо :)

**Comment by xaionaro** [comment]
> Пример, я использую mktemp для создания временного файла, куда можно записать ошибки от rsync:
> `tmpfile=$(mktemp -p "/srv/clsync/error/" clsync-rsync-"$LABEL".err.XXXXXXXXXX)`
> `rsync ... 2>"${tmpfile}"`

Хитро́ Вы придумали)

> Если здесь exec преследует другую какую то цель, то подскажите пожалуйста какую? Спасибо :)

Не, я просто подчёркивал, что к этому моменту скрипт закончил делать всё, что ему нужно было делать, и теперь всё остаётся только за `rsync`-ом. А в вашем случае это действительно лишнее.

**Comment by vebmaster** [comment]
не я придумал, скопировал откуда то :) 
Не понимал полтора месяца почему файлы остаются и не удаляются. Вот только сегодня решил задать вопрос про mktemp, начал думать, что это clsync как то модифицирует запуск.
Еле заметил, что запуск идёт через exec. Дальше гугл помог.
