### ISSUE TITLE
Could be a double unlock on the lock bsm_mutex_prefetcher

### ISSUE THREAD

**Issue by ycaibb** [xaionaro/clsync#181]
HI, it seems the lock  `bsm_mutex_prefetcher` could be freed double in the below code when it goes to default. But, I don't know whether it is possible in reality to go to the `default`. Looking forward to the discussion.

I think, there is a missed return in the `default`?

```
int bsm_wait_prefetched ( struct ctx *ctx_p, struct indexes *indexes_p, struct timeval *timeout_p )
{
	...;
	pthread_mutex_lock ( &bsm_mutex_prefetcher );

	...;


	if ( ( errno = pthread_cond_timedwait ( &bsm_cond_gotevent, &bsm_mutex_prefetcher, &ts_abs ) ) ) {
		pthread_mutex_unlock ( &bsm_mutex_prefetcher ); // free first time


		switch ( errno ) {
			case ETIMEDOUT:
				critical_on ( mondata->event_count );
				debug ( 2, "Timed out -> no events (mondata->event_count == %i)", mondata->event_count );
				return 0;
			default:
				critical ( "Got unhandled error on pthread_cond_timedwait()" );
		}
	}

	pthread_mutex_unlock ( &bsm_mutex_prefetcher ); // free second time
	...;
	return mondata->event_count;
}
```

Best,

https://github.com/clsync/clsync/blob/2202ec0f7c2f74810dbb8f27ff962a524b501e1c/sync.c#L3318-L3321

**Comment by xaionaro** [comment]
Hello!

Thank you for looking into this. I'm wondering have you faced a problem where you suspect a deadlock or you are just looking through the code and found this issue?

As for double-free: when `critical` is called, the application just exits (function `exit` is called) and no further lines of code are executed.

**Comment by ycaibb** [comment]
@xaionaro Hi, thank you for your time and explaination. I use a code scanner to find them.
