### ISSUE TITLE
Doesn't build on Debian Squeeze

### ISSUE THREAD

**Issue by xaionaro** [xaionaro/clsync#84]
```
fileutils.c:180: error: ‘O_PATH’ undeclared (first use in this function)
fileutils.c:180: error: (Each undeclared identifier is reported only once
fileutils.c:180: error: for each function it appears in.)
```

**Comment by fabianito** [comment]
Hi, 
squeeze is quite old - but for all the need clsync on squeeze: it works :)
I've build a chroot wheeze and build it with:
`aclocal
autoreconf -i
./configure && make`
After the sucessful build, we need the libs:

 `ldd clsync|while read line; do echo "$line"; done |awk '{print $3}'`
 `tar -czpf libs.tgz  $(ldd clsync | while read line; do echo "$line" |grep "/"; done |awk '{print $3}) `
 `tar -czpf clsync-0.4.2-master.tgz clsync man/ libs.tgz `

Next Step is to copy the clsync-0.4.2-master.tgz to your squeeze installation and extract all files and set the LD_LIBRARY_PATH:

`mkdir clsync-master`
`cd clsync-master/`
`tar -xzf ../clsync-0.4.2-master.tgz`
`tar -xzf libs.tgz`
`export LD_LIBRARY_PATH=/root/clsync-master/lib:/root/clsync-master/usr/lib`
